# Generated by Django 2.2.7 on 2019-12-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191128_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('serie', models.TextField(max_length=5)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
    ]
